from pydantic import BaseModel

class ClinicalData(BaseModel):
    Age: int
    Gender: str
    Ethnicity: str
    EducationLevel: str
    BMI: float
    Smoking: str
    AlcoholConsumption: str
    PhysicalActivity: str
    DietQuality: str
    SleepQuality: str
    FamilyHistoryAlzheimers: str
    CardiovascularDisease: str
    Diabetes: str
    Depression: str
    HeadInjury: str
    Hypertension: str
    SystolicBP: int
    DiastolicBP: int
    CholesterolTotal: int
    CholesterolLDL: int
    CholesterolHDL: int
    CholesterolTriglycerides: int
    MMSE: float
    FunctionalAssessment: str
    MemoryComplaints: str
    BehavioralProblems: str
    ADL: str
    Confusion: str
    Disorientation: str
    PersonalityChanges: str
    DifficultyCompletingTasks: str
    Forgetfulness: str
    Diagnosis: str
    DoctorInCharge: str