from pydantic import BaseModel, Field
from typing import Optional

class ClinicalData(BaseModel):
    Age: Optional[int] = Field(None)
    Gender: Optional[int] = Field(None)
    Ethnicity: Optional[int] = Field(None)
    EducationLevel: Optional[int] = Field(None)
    BMI: Optional[float] = Field(None)
    Smoking: Optional[int] = Field(None)
    AlcoholConsumption: Optional[float] = Field(None)
    PhysicalActivity: Optional[float] = Field(None)
    DietQuality: Optional[float] = Field(None)
    SleepQuality: Optional[float] = Field(None)
    FamilyHistoryAlzheimers: Optional[int] = Field(None)
    CardiovascularDisease: Optional[int] = Field(None)
    Diabetes: Optional[int] = Field(None)
    Depression: Optional[int] = Field(None)
    HeadInjury: Optional[int] = Field(None)
    Hypertension: Optional[int] = Field(None)
    SystolicBP: Optional[int] = Field(None)
    DiastolicBP: Optional[int] = Field(None)
    CholesterolTotal: Optional[float] = Field(None)
    CholesterolLDL: Optional[float] = Field(None)
    CholesterolHDL: Optional[float] = Field(None)
    CholesterolTriglycerides: Optional[float] = Field(None)
    FunctionalAssessment: Optional[float] = Field(None)
    MemoryComplaints: Optional[int] = Field(None)
    BehavioralProblems: Optional[int] = Field(None)
    ADL: Optional[float] = Field(None)
    Confusion: Optional[int] = Field(None)
    Disorientation: Optional[int] = Field(None)
    PersonalityChanges: Optional[int] = Field(None)
    DifficultyCompletingTasks: Optional[int] = Field(None)
    Forgetfulness: Optional[int] = Field(None)

    # Propriedades que **não podem ser passadas** na requisição
    MMSE: Optional[float] = Field(None, exclude=True)
    Diagnosis: Optional[int] = Field(None, exclude=True)
    DoctorInCharge: Optional[str] = Field(None, exclude=True)
