version: "3.8"

services:
  alzheimer-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: alzheimer_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CUDA_VISIBLE_DEVICES=0 # Enable GPU if available
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
